### ISSUE TITLE
Serverless render

### ISSUE THREAD

**Issue by v-moravec** [Dave136/vue-email#117]
Hello, is it possible to use `useCompiler` with Nuxt on serverless? In older versions it seemed to work, now I can't deploy to Vercel Edge without errors and when I deploy to their serverless functions (AWS Lambda - node), I get back just plain text.

What I get locally:
![image](https://github.com/Dave136/vue-email/assets/61109712/78c6adee-edda-487e-bfbe-097ffdb650bc)
On Vercel Severless:
![image](https://github.com/Dave136/vue-email/assets/61109712/90d886cf-e84a-4868-b3dc-e37f31ca90ed)

**Comment by iBobik** [comment]
How is it send exactly? Can you send here whole message source? (Version send from localhost and from Vercel.)

**Comment by v-moravec** [comment]
You can look at the source compiled by vueemail here - https://ldseating.vercel.app/api/email/registration

API endpoint looks like this:

```ts
import { useCompiler } from '#vue-email'

export default defineEventHandler(async (event) => {
  const locale = getHeader(event, 'Accept-Language')

  return await useCompiler('Registration.vue', {
    i18n: { defaultLocale: typeof locale === 'string' ? locale : 'en' },
  })
})

```

And template looks like this:

```vue
<template>
  <Base
    :heading="$t('registration.title')"
    :preview-text="$t('registration.title')"
  >
    <template>
      <e-text class="text-[14px] leading-[24px] text-black">
        {{ $t('base.greetings') }}
      </e-text>
      <e-text class="text-[14px] leading-[24px] text-black">
        {{ $t('registration.content') }}
      </e-text>
      <e-text class="text-[14px] leading-[24px] text-black">
        {{ $t('registration.warning') }} info@ldseating.com
      </e-text>
    </template>
  </Base>
</template>

```

Directory structure - all templates are in `/emails` folder as well as the base wrapper.

**Comment by v-moravec** [comment]
Well, sometimes the function even crashes. I'm getting a lot of 500 right now.

**Comment by v-moravec** [comment]
I found some errors in logs:
```bash
Error loading component Error: [@vue/compiler-sfc] Failed to resolve import source "~/emails/types".

Base
50 |  import { BaseProps } from '~/emails/types'
51 |  
52 |  const props = defineProps<BaseProps>()
   |                            ^^^^^^^^^
53 |  </script>
54 |  
    at ScriptCompileContext.error (/var/task/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:15841:11)
    at importSourceToScope (/var/task/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:18428:16)
    at resolveTypeFromImport (/var/task/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:18393:23)
    at innerResolveTypeReference (/var/task/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:18299:14)
    at resolveTypeReference (/var/task/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:18288:36)
    at innerResolveTypeElements (/var/task/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:17945:24)
    at resolveTypeElements (/var/task/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:17902:35)
    at resolveRuntimePropsFromType (/var/task/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:19312:20)
    at genRuntimePropsFromTypes (/var/task/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:19288:17)
    at genRuntimeProps (/var/task/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:19278:18)
```

But there are multiple errors - all connected with types, which is weird, because the template I'm trying to use should only need `BaseProps`.

![image](https://github.com/Dave136/vue-email/assets/61109712/9e87fc83-2004-4522-b582-2a7d9e8aeb15)

Here is the error when building with `vercel-edge` preset (the same happens with `cloudflare-pages` preset):

```bash
 ERROR  Cannot resolve "react-dom/server" from "/Users/vojtechmoravec/WebstormProjects/LD_Seating/ld-seating-next/node_modules/.pnpm/@vue+compiler-sfc@3.3.4/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js" and externals are not allowed!
```

**Comment by Flowko** [comment]
importing types is not supported yet, you need to have that type inside the email template you wanna use, till we add that, thats the only solution for now

**Comment by v-moravec** [comment]
I made a minimal reproduction - https://github.com/v-moravec/vue-email-edge. It is not possible to build for CF Pages and Vercel Edge. Even without the types. @Flowko

**Comment by Flowko** [comment]
Thanks for the reproduction, rn we are working on moving the repo to an organization and split the tempaltes, to make it easier to fix bugs, but we will do check this
