### ISSUE TITLE
'[nuxt] [request error] [unhandled] [500] 'import' statement of ES modules is not supported' on /server/api/send-email.post.ts with Nuxt3

### ISSUE THREAD

**Issue by AvalonAlgo** [Dave136/vue-email#60]
Clicking a button on my UI invokes

```
const handleSend = async () => {
  const mail = await useFetch('/api/send-email', {
    method: 'POST'
  })
}`
```
which reaches the api route of 

```
// server/api/send-email.post.ts
import {useCompiler} from '#vue-email';
import sendgrid from '@sendgrid/mail';

sendgrid.setApiKey(process.env.SENDGRID_API_KEY || '');

export default defineEventHandler(async (event) => {
  const template = await useCompiler('welcome.vue', {
    url: 'https://vuemail.net/',
  })

  const options = {
    from: 'you@example.com',
    to: 'user@gmail.com',
    subject: 'hello world',
    html: template,
  };

  await sendgrid.send(options);
  return { message: 'Email sent' };
});
```

, and returns an error code of 500 with explanation 

```
[nuxt] [request error] [unhandled] [500] 'import' statement of ES modules is not supported
Use asynchronous function 'importFromString' instead or replace it with dynamic 'import()' expression.
  at importFromStringSync (/C:/Users/deniz/Documents/Code/nuxtcv/node_modules/module-from-string/dist/index.mjs:247:13)                                                         20:30:54  
  at templateRender (/C:/Users/deniz/Documents/Code/nuxtcv/.nuxt/dev/index.mjs:19215:21)      
  at useCompiler (/C:/Users/deniz/Documents/Code/nuxtcv/.nuxt/dev/index.mjs:19293:26)
  at async /C:/Users/deniz/Documents/Code/nuxtcv/.nuxt/dev/index.mjs:19309:20
  at async Object.handler (/C:/Users/deniz/Documents/Code/nuxtcv/node_modules/h3/dist/index.mjs:1683:19)
  at async Server.toNodeHandle (/C:/Users/deniz/Documents/Code/nuxtcv/node_modules/h3/dist/index.mjs:1893:7)

```

Other api routes work just fine.

**Comment by Dave136** [comment]
hi @AvalonAlgo, 

can you show me the template? Can u replicate the error?

**Comment by AvalonAlgo** [comment]
hi @Dave136 ,

I saw the closed issue https://github.com/Dave136/vue-email/issues/51 , and following it I removed the import statements from the template I was using: 

```
<script lang="ts" setup>
import { EButton, EHtml } from 'vue-email';

defineProps<{ url: string }>();
</script>


<template>
  <e-html lang="en">
    <e-button :href="url">
      View on GitHub
    </e-button>
  </e-html>
</template>
```
It worked perfectly without the extra import statements and I received and email in my inbox. @Flowko seems to have updated the docs, and this template had been sitting in my project structure for longer than that, that's why I was confused.

**Comment by Dave136** [comment]
Perfect! We'll update the docs, to avoid the confused

**Comment by davesawatzky** [comment]
I had the same error.  I removed the vue-email imports from my template, but now it doesn't recognize any of my other imports either.  I keep getting 'Error: Cannot find module '../....'  I'm trying to import Pinia stores to the template.

`Error: Cannot find module '../stores/userPerformer'
Require stack:
- C:\Users\daves\Documents\Web Development\projects\wmf-nuxt\.nuxt\dev\fpVHJzJxIZghROlfv8Rnp.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at C:\Users\daves\Documents\Web Development\projects\wmf-nuxt\.nuxt\dev\fpVHJzJxIZghROlfv8Rnp.js:36:28
    at Script.runInContext (node:vm:135:12)
    at Script.runInNewContext (node:vm:140:17)
    at runInNewContext (node:vm:292:38)
    at requireFromString (file:///C:/Users/daves/Documents/Web%20Development/projects/wmf-nuxt/node_modules/.pnpm/module-from-string@3.3.0/node_modules/module-from-string/dist/index.mjs:130:3)   
    at importFromStringSync (file:///C:/Users/daves/Documents/Web%20Development/projects/wmf-nuxt/node_modules/.pnpm/module-from-string@3.3.0/node_modules/module-from-string/dist/index.mjs:244:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\daves\\Documents\\Web Development\\projects\\wmf-nuxt\\.nuxt\\dev\\fpVHJzJxIZghROlfv8Rnp.js'
  ]
}`
